DROP TABLE IF EXISTS prueba;

CREATE TABLE Alumn_Data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT NOT NULL,
    user TEXT NOT NULL,
    pass1 TEXT NOT NULL,
    pass2 TEXT NOT NULL
);